---
- name: Ensure required packages are installed
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: keepalived
    state: present
  when:
    - ansible_facts.os_family == "Debian"

- name: Copy keepalived.conf template to host
  ansible.builtin.template:
    src: templates/keepalived.conf.j2
    dest: "/etc/keepalived/keepalived.conf"
    mode: '0644'
  become: true

- name: Restart keepalived to reload configuration
  ansible.builtin.service:
    name: keepalived
    state: restarted